### ISSUE TITLE
Client cannot retrieve Query result

### ISSUE THREAD

**Issue by sero583** [CloudburstMC/Protocol#43]
# Description of issue
Somewhere at sending the response of a query request back to the client (MC:Bedrock W10, v.1.14.60, Protocol Version 390) is not working. I used my own software, but also ProxyPass to identify if this is an issue made by myself or a general issue. It is a general as it seems. Proxypass kicks my client at login sequence "Invalid Idenity Public Key". It is running under localhost (or lets say 0.0.0.0/127.0.0.0 whatever..) with its default settings.

## Exception in console
```
[18:49:52 DEBUG]: Is player data valid? true
[18:49:52 DEBUG]: Initializing proxy session
[18:49:52 DEBUG]: Packets will be logged under C:\Users\serha\OneDrive\Desktop\ProxyPass (MITM)\.\sessions\sero583-1590684592701\packets.log
[18:49:52 DEBUG]: Downstream connected
[18:49:53 ERROR]: An exception occurred in RakNet
java.lang.IllegalStateException: Connection has been closed
        at com.nukkitx.protocol.bedrock.BedrockSession.checkForClosed(BedrockSession.java:71) ~[proxypass.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockClientSession.disconnect(BedrockClientSession.java:13) ~[proxypass.jar:?]
        at com.nukkitx.proxypass.network.bedrock.session.ProxyPlayerSession.lambda$new$0(ProxyPlayerSession.java:54) ~[proxypass.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.close(BedrockSession.java:252) ~[proxypass.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$Server.onDisconnect(BedrockRakNetSessionListener.java:90) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.close(RakNetSession.java:637) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDisconnectionNotification(RakNetSession.java:862) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:294) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:428) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:406) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:399) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:273) ~[proxypass.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[proxypass.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [proxypass.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [proxypass.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [proxypass.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [proxypass.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [proxypass.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [proxypass.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [proxypass.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [proxypass.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [proxypass.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [proxypass.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [proxypass.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [proxypass.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [proxypass.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [proxypass.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
```

**Comment by rtm516** [comment]
Are you using BDS and if so try disabling online mode

**Comment by sero583** [comment]
@rtm516 What is meant by BDS? I run the default configuration.

**Comment by rtm516** [comment]
Bedrock Dedicated Server (the official one given by Microsoft)

**Comment by sero583** [comment]
No? I see you do not understand the issue.

Since after many months later a reaction finally came I wasn't immediately sure what this issue was.

I remember that it was the issue when going with Bedrock client on servers tab and waiting for the query response of the server.

I do not use BDS.
